server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        native:
          search-locations: classpath:/shared
#    config:
#      server:
#        git:
#          uri: https://github.com/StevenSansan/OrderSystem.git #git仓库地址
#          searchPaths: config #仓库路径
#          username: HandCap #git仓库用户名
#          password: Chinese1!, #git仓库密码
#      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/